url: "www.fancy4n6.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Fancy Forensics" # the name of your site, e.g. ACME Corp.
description: "Digital forensics & incident response research and writeups"

# Social media links
# ========================================================================================
github_username: shannaniggans
twitter_username: fancy_4n6

# Plugins and Plugin Configuration
# ========================================================================================
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Other Plugins & configuration
# ---------------------------------------------------------------------------------------
tag_dir: tag
highlighter: rouge
markdown: redcarpet

    # File inclusion/exclusion
# ========================================================================================

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock