# Site
title: "Fancy Forensics"
description: "Digital forensics & incident response research and writeups."
logo: 'assets/images/fancy4n6-header.png'
favicon: 'assets/images/favicon.ico'
baseurl: ""
google_analytics: 'G-WV2F0X9QJ6'
# disqus: 'demowebsite'
include: ["_pages"]
permalink: /:title/

# Tags
tag_dir: tag

# Authors
authors:
  shanna:
    name: Shanna
    display_name: Shanna
    avatar: 'assets/images/avatar.png'
    #email: wowthemesnet@gmail.com
    #web: https://www.wowthemes.net
    twitter: https://twitter.com/fancy_4n6
    description: "Shanna's description"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 10
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
